### ISSUE TITLE
Larger receiver area

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#13]
Try to create a larger stockpile outside Unloaders. Maybe 3x3 or 2x4 'Deepdriller' style. Should be a new building as the current Unloader is small, very handy, and just fine as it is.

**Comment by TehJoE** [comment]
I've been thinking about this one for a while, trying to figure out a realistic machine that would be able to perform this function. Perhaps some kind of overhead device similar to those 50-cent claw games? It'd scale nicely but without animations it may not be easy to tell what it actually is. Animating it would be a pain, with synchronizing item drop locations and all, so I'd like to avoid that if possible. 

Does anyone have any other ideas?

**Comment by noone57** [comment]
Well, I've never been 100% certain about this one. Mostly because To some extent, you can already built a larger receivers area from the available pieces ... e.g. use some splitters and Unloaders side-by-side, etc ... 

I guess we should first identify what the advantage of a larger receiver area would be. From memory (and some old discussion of the RM forum), there were two aspects that people had in mind: 1) have multiple drop points of the belt to avoid jams (e.g. small stack of potatoes on the ground, strawberries on the belt: the cook will not grab the potatoes, and the belt will never move again). As I said above, this can be custom built with some clever Splitter and Unloaders pairs.

The other aspect was to remove the need for colonists to move back and forth between the end of the belt and the stock-pile. I.e. basically have the belt directly build a full stockpile. Now, as is has been shown before, you can in fact already do that by simply keeping items on the belt, and line up many unloaders. 

So, in the end, I don't see the need for a larger receiver anymore ...

**Comment by ForsakenShell** [comment]
Yes, with the selectors add-on this is more an issue of rethinking your approach to your belt layout.  I don't see a practical need for another unloader component.

**Comment by noone57** [comment]
Alright, let's then close this issue. We can always re-open one later if the need was to arise. But I think for now, we agree this is not something useful - and definitely not in the main mod.
