### ISSUE TITLE
Thermal features + weather impact

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#15]
Should add some proper heat generation for some of the belt items (small, but non-zero). Would also be good to add some weather consequences: deep cold = freeze belts. Can be fixed by research -> more power required to heat the components / improve electrical system to reduce heat (in hot regions).

**Comment by TehJoE** [comment]
I'm gonna split the heat-blocking aspect of this into its own issue, as I want to reference it as fixed in a commit but don't want it to auto-close the other enhancements in this issue.

**Comment by noone57** [comment]
Good idea.
