### ISSUE TITLE
Loaders should spawn with no preference

### ISSUE THREAD

**Issue by noone57** [A2Bcorp/RW_A2B#27]
As suggested by FamousShoes on the forum:

11: Use an empty list for new loaders so one doesn't have to watch a loader-blueprint until it's built then jump in quickly before bad items, e.g., ones without an unloader, are placed into the system.

**Comment by TehJoE** [comment]
This has actually been bugging me for a while. I honestly don't know why I
haven't changed it, I installed a mod to do the exact same thing for
stockpiles on my playing-the-actual-game install.
