### ISSUE TITLE
Unable to build Undercovers under Walls

### ISSUE THREAD

**Issue by CovertJaguar** [A2Bcorp/RW_A2B#41]
I can build an Undercover and place a wall blueprint on it, but no one will ever build it and I can't force anyone to do so. Or I can build a wall and place a Undercover blueprint under it, but again no one will ever build it.

I'm wondering if it might be a mod conflict of some kind.

Mods:
 * AlphaMuffalo1.7
 * AutoHuntBeacon
 * Common
 * Core
 * EdBInterface
 * EdBModOrder
 * Icons
 * OmniFactions
 * OmniWeapons
 * RW_A2B
 * SCA10Core
 * VeinMiner

**Comment by noone57** [comment]
Thanks for the report. I can confirm the bug in the mod alone - this is definitely not a mod conflict. 
I'll look into this. The Undercover ought to behave as floors, but obviously they don't ... Also, it seems that the 'inaccessible' blueprint (either wall or Undercover) becomes accessible as soon as the other exiting element at the same place is deconstructed ...

**Comment by TehJoE** [comment]
Perhaps we should treat the Undercovers as conduits rather than floors.
Then they should natively build under anything the Pawns can reach. They
wouldn't necessarily have to transmit power, but honestly it would make
sense if they did.

**Comment by noone57** [comment]
Actually, that's what I did (i.e. make them behave like power conduits, and they do transmit power). Was mistaken in my earlier post when I wrote "floor". But there's definitely still something off with them ...

**Comment by ForsakenShell** [comment]
Ok, this issue is now fixed by a little xml editing and (fillPercent must be 0 for undercovers) and is implemented.

Thanks everyone.
