### ISSUE TITLE
Teleporter visual anomaly

### ISSUE THREAD

**Issue by ForsakenShell** [A2Bcorp/RW_A2B#43]
Since the teleporter/receiver pair was moved to it's own add-on and the teleporter was changed from a 2x2 building to a 2x1 building, there is a visual anomaly with item rendering.  This doesn't affect the actual function of the teleporter/receiver but it's visually jarring.

I mentioned this to noone on the Ludeon forums:

1000101:
> There is a small issue with the rendering of items on the teleporter due to it still using the same offset logic from when it was 2x2.  I tried to get that resolved but wasn't sure about the logic (code with no comments, yay!) so I didn't get very far on that front.  I suppose I could have gotten it going if I spent more time on it, but I think I'm done for tonight.  It's just a graphic glitch, nothing game breaking.  That can be resolved in v0.11.1 or something.

noone:
> Regarding the visual glitch for the teleporter, I had a look at the code (and the nasty uncommented lines I wrote way back when...;-). I am fairly sure that the issue is with line 155 in BeltTeleporterComponent.cs :
>
> midDirection = parent.Position + parent.Rotation.FacingCell - ThingOrigin;
>
> should be (I think) : midDirection = parent.Position;
>
> I won't have time to test this much more, unfortunately. Things are crazy for me these days ...

**Comment by TehJoE** [comment]
Fixed in https://github.com/A2Bcorp/RW_A2B_Teleporter/commit/cdd9a97c44fc65f890faa49ad02317f321d01ced
