### ISSUE TITLE
Move add-on issues to respective repos' issue trackers

### ISSUE THREAD

**Issue by TehJoE** [A2Bcorp/RW_A2B#45]
Should we move issues related to teleporters, selectors, etc to their own repos' issue trackers? It will make it a lot easier to auto-close them through commit logs and keep them separated and associated with the component they affect.

**Comment by noone57** [comment]
Yes, good idea. Extending along the same idea, what about the user manual ? 

Should we have just the one wiki with multiple pages, or different wikis for the different extensions ? It's probably less critical, but given that we have two distinct "teams" for the add-ons and the core mod, I suspect we may one day get add-oners without access to the main mod ... so, having the user manual of the add-ons directly in the add-ons repository would be preferential ...

**Comment by TehJoE** [comment]
I agree. Compartmentalizing as much as possible will help us maintain the
separation of the addons. There's not much sense having the wiki pages all
in one spot other than for convenience, and if we really want we can link
to the addons' wikis from the main mod's.

**Comment by TehJoE** [comment]
Looks like this is already pretty much implemented by now.
