### ISSUE TITLE
Research Tab is blank when mod is loaded

### ISSUE THREAD

**Issue by grumpyalchemist** [A2Bcorp/RW_A2B#53]
![screenshot 2016-02-10 17 54 24](https://cloud.githubusercontent.com/assets/17169078/12964695/932e73ee-d01f-11e5-8064-b30a0cb432b4.png)
![screenshot 2016-02-10 17 57 00](https://cloud.githubusercontent.com/assets/17169078/12964727/ba54aa88-d01f-11e5-87f5-8b59656fcd38.png)
![screenshot 2016-02-10 17 57 33](https://cloud.githubusercontent.com/assets/17169078/12964736/cba8cd64-d01f-11e5-8136-00014904d7f4.png)

**Comment by ForsakenShell** [comment]
This error is actually associated with a bug in the [Community Core Library](https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/issues) research menu.
