### ISSUE TITLE
alpha 14

### ISSUE THREAD

**Issue by super9mega** [A2Bcorp/RW_A2B#57]
aplha 14 is broken, the dll reference to verse and loadedmodmanager is broken, when i try to correct it gives " error CS0246: The type or namespace name 'LoadedMod' could not be found (are you missing a using directive or an assembly reference?)"

**Comment by ForsakenShell** [comment]
I haven't done the Alpha 14 update yet so it can hardly be broken.

**Comment by super9mega** [comment]
well, i figured out that issue - "LoadedMod" has now become "ModContentPack" and your "mod.RootFolder" has become "mod.RootDir" 

(for when you update) 

also, you need to add <techLevel>Industrial</techLevel> to all the research and change -totalCost-%number here%-/totalCost- to -baseCost-%number here%-/baseCost- (-- == ><)

**Comment by super9mega** [comment]
(forked with all changes needed to build) (still has issues with keybinds and divide by zero when trying to use belts)

**Comment by ForsakenShell** [comment]
I know what needs to be done, I just haven't done it yet.  I've been too busy with other mods such as CCL and my ESM series.

Please be patient.
